name: money_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.9+9

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  flutter_login: ^5.0.0
  flutter_screen_lock: ^9.1.0
  flutter_app_lock: ^4.1.1+1
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2
  syncfusion_flutter_charts: ^27.1.53
  day_night_time_picker: ^1.3.1
  flutter_material_pickers: ^3.7.0
  sliding_up_panel: ^2.0.0+1
  keyboard_actions: ^4.2.0
  fluttertoast: ^8.2.8
  flutter_swipe_action_cell: ^3.1.5
  share_plus: ^10.1.0
  in_app_review: ^2.0.9
  rate_my_app: ^2.2.0

  # icons
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.7.0
  outline_material_icons: ^1.0.0
  flutter_boxicons: ^3.1.0
  icofont_flutter: ^1.4.0

  cupertino_icons: ^1.0.8
  path: ^1.9.0

dependency_overrides:
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#ffffff"
  image: images/splash_screen.png
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/project/localization/lang/
    - images/
